"""
Generates PowerShell scripts for Cisco ETD Exchange Online configuration.
"""


def _ps_array(items):
    """Convert a Python list to a PowerShell array string."""
    quoted = [f'"{item}"' for item in items]
    return "@(" + ", ".join(quoted) + ")"


def _ps_functions():
    return """\
function Check-Object {
    param ([string]$Name, [scriptblock]$Command)
    try {
        & $Command | Out-Null
        Write-Host "$Name : CONFIGURED" -ForegroundColor Green
    } catch {
        Write-Host "$Name : NOT CONFIGURED" -ForegroundColor Yellow
    }
}

function Install-Object {
    param ([string]$Name, [scriptblock]$Command)
    Write-Host "Installing $Name ..." -ForegroundColor Cyan
    try {
        & $Command
        Write-Host "$Name installed successfully." -ForegroundColor Green
    } catch {
        Write-Host "ERROR installing $Name : $($_.Exception.Message)" -ForegroundColor Red
        Disconnect-ExchangeOnline -Confirm:$false
        exit 1
    }
}

function Remove-Object {
    param ([string]$Name, [scriptblock]$Command)
    Write-Host "Removing $Name ..." -ForegroundColor Cyan
    try {
        & $Command
        Write-Host "$Name removed successfully." -ForegroundColor Yellow
    } catch {
        Write-Host "ERROR removing $Name : $($_.Exception.Message)" -ForegroundColor Red
    }
}
"""


def generate_script(config):
    """
    Generate a complete PowerShell script based on configuration.

    config keys:
        admin_upn         : str
        journal_address   : str
        deployment_mode   : "Journaling" | "Inline"
        flows             : dict {inbound, outbound, internal} (Inline only)
        etd_ips           : list[str]  - Cisco ETD IP addresses
        smart_host        : str        - Outbound smart host
        seg_in_front      : bool
        seg_ips           : list[str]
        xpass_value       : str
        geo               : str
        operation         : "verify" | "install" | "remove"
    """
    mode      = config["deployment_mode"]
    admin_upn = config["admin_upn"]
    journal   = config["journal_address"]
    operation = config["operation"]
    flows     = config.get("flows", {})
    etd_ips              = config.get("etd_ips", [])
    smart_host           = config.get("smart_host", "")
    outbound_rule_enabled = config.get("outbound_rule_enabled", True)
    seg_front            = config.get("seg_in_front", False)
    seg_ips   = config.get("seg_ips", [])
    xpass     = config.get("xpass_value", "12345")
    geo       = config.get("geo", "")

    # IPs to use for inbound connector and bypass rule
    source_ips = seg_ips if (seg_front and seg_ips) else etd_ips

    lines = []

    # Header
    lines += [
        "# =========================================================",
        "# Cisco Secure Email Threat Defense - Exchange Online",
        f"# Mode        : {mode}",
        f"# GEO         : {geo}",
        f"# Operation   : {operation.upper()}",
        f"# Admin UPN   : {admin_upn}",
        "# Generated by ETD Configurator",
        "# =========================================================",
        "",
    ]

    # Helper functions
    lines += [_ps_functions()]

    # --- Variable declarations ---
    lines += [f'$AdminUPN          = "{admin_upn}"']
    lines += [f'$JournalAddress    = "{journal}"']
    lines += [f'$JournalNdrAddress = "{admin_upn}"']

    if mode == "Inline":
        if flows.get("inbound"):
            lines += [
                '$InboundConnectorName = "Cisco Secure Email Threat Defense Inbound"',
                '$BypassRuleName       = "Cisco Secure Email Threat Defense Bypass Spam Filter"',
                '$QuarantineRuleName   = "Cisco Secure Email Threat Defense Quarantine Rule"',
                '$JunkRuleName         = "Cisco Secure Email Threat Defense Junk Rule"',
            ]
        if flows.get("outbound"):
            rule_state = "$true" if outbound_rule_enabled else "$false"
            lines += [
                '$OutboundConnectorName  = "Cisco Secure Email Threat Defense Outbound"',
                '$OutboundTagRuleName    = "Cisco Secure Email Threat Defense Outbound Tag"',
                f'$OutboundSmartHost      = "{smart_host}"',
                f'$XPassValue             = "{xpass}"',
                f'$OutboundTagRuleEnabled = {rule_state}',
            ]
        if flows.get("internal"):
            lines += ['$JournalRuleName = "Cisco Secure Email Threat Defense"']
    else:
        lines += [
            '$JournalRuleName          = "Cisco Secure Email Threat Defense"',
            '$JournalConnectorName     = "Cisco ETD Journaling Direct"',
            '$JournalDomain            = ($JournalAddress -split "@")[1]',
        ]

    if source_ips:
        lines += [f"$CiscoIPs = {_ps_array(source_ips)}"]

    lines += [""]

    # --- Connect ---
    lines += [
        'Write-Host ""',
        'Write-Host "Connecting to Exchange Online..." -ForegroundColor Cyan',
        "Connect-ExchangeOnline -UserPrincipalName $AdminUPN -ShowBanner:$false",
        "",
    ]

    # --- Operation body ---
    if operation == "verify":
        lines += _verify_block(mode, flows)
    elif operation == "install":
        lines += _install_block(mode, flows, source_ips)
    elif operation == "remove":
        lines += _remove_block(mode, flows)

    # --- Disconnect ---
    lines += [
        "",
        "Disconnect-ExchangeOnline -Confirm:$false",
        'Write-Host ""',
        'Write-Host "Operation completed." -ForegroundColor Cyan',
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# VERIFY
# ---------------------------------------------------------------------------

def _verify_block(mode, flows):
    lines = []
    if mode == "Inline":
        if flows.get("inbound"):
            lines += [
                'Write-Host ""',
                'Write-Host "--- INBOUND CONNECTOR ---"',
                "Check-Object $InboundConnectorName { Get-InboundConnector -Identity $InboundConnectorName -ErrorAction Stop }",
                'Write-Host ""',
                'Write-Host "--- TRANSPORT RULES (INCOMING) ---"',
                "Check-Object $BypassRuleName     { Get-TransportRule -Identity $BypassRuleName     -ErrorAction Stop }",
                "Check-Object $QuarantineRuleName { Get-TransportRule -Identity $QuarantineRuleName -ErrorAction Stop }",
                "Check-Object $JunkRuleName       { Get-TransportRule -Identity $JunkRuleName       -ErrorAction Stop }",
            ]
        if flows.get("outbound"):
            lines += [
                'Write-Host ""',
                'Write-Host "--- OUTBOUND CONNECTOR ---"',
                "Check-Object $OutboundConnectorName { Get-OutboundConnector -Identity $OutboundConnectorName -ErrorAction Stop }",
                'Write-Host ""',
                'Write-Host "--- TRANSPORT RULES (OUTGOING) ---"',
                "Check-Object $OutboundTagRuleName { Get-TransportRule -Identity $OutboundTagRuleName -ErrorAction Stop }",
            ]
        if flows.get("internal"):
            lines += [
                'Write-Host ""',
                'Write-Host "--- JOURNAL RULE (INTERNAL) ---"',
                "Check-Object $JournalRuleName { Get-JournalRule -Identity $JournalRuleName -ErrorAction Stop }",
            ]
    else:
        lines += [
            'Write-Host ""',
            'Write-Host "--- JOURNALING NDR ---"',
            "try {",
            "    $tc = Get-TransportConfig -ErrorAction Stop",
            "    if ($tc.JournalingReportNdrTo) {",
            '        Write-Host "Journaling NDR Address : $($tc.JournalingReportNdrTo)" -ForegroundColor Green',
            "    } else {",
            '        Write-Host "Journaling NDR Address : NOT CONFIGURED" -ForegroundColor Yellow',
            "    }",
            "} catch {",
            '    Write-Host "Unable to retrieve Transport Config" -ForegroundColor Red',
            "}",
            'Write-Host ""',
            'Write-Host "--- JOURNAL RULE ---"',
            "Check-Object $JournalRuleName { Get-JournalRule -Identity $JournalRuleName -ErrorAction Stop }",
            'Write-Host ""',
            'Write-Host "--- JOURNALING OUTBOUND CONNECTOR ---"',
            "Check-Object $JournalConnectorName { Get-OutboundConnector -Identity $JournalConnectorName -ErrorAction Stop }",
        ]
    return lines


# ---------------------------------------------------------------------------
# INSTALL
# ---------------------------------------------------------------------------

def _install_block(mode, flows, source_ips):
    lines = []
    needs_journal = (mode == "Journaling") or (mode == "Inline" and flows.get("internal"))

    # NDR address (required before creating any journal rule)
    if needs_journal:
        lines += [
            "# ── Journaling NDR Address ───────────────────────────",
            "$tc = Get-TransportConfig",
            "if (-not $tc.JournalingReportNdrTo) {",
            '    Write-Host "Configuring Journaling NDR address..." -ForegroundColor Cyan',
            "    try {",
            "        Set-TransportConfig -JournalingReportNdrTo $JournalNdrAddress -ErrorAction Stop",
            '        Write-Host "Journaling NDR address set to $JournalNdrAddress" -ForegroundColor Green',
            "    } catch {",
            '        Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red',
            "        Disconnect-ExchangeOnline -Confirm:$false",
            "        exit 1",
            "    }",
            "} else {",
            '    Write-Host "Journaling NDR already configured: $($tc.JournalingReportNdrTo)" -ForegroundColor Green',
            "}",
            "",
        ]

    if mode == "Inline":
        if flows.get("inbound"):
            lines += [
                "# ── Inbound Connector ────────────────────────────────",
                "if (-not (Get-InboundConnector -Identity $InboundConnectorName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $InboundConnectorName {",
                "        New-InboundConnector `",
                "            -Name $InboundConnectorName `",
                "            -ConnectorType Partner `",
                "            -SenderDomains '*' `",
                "            -SenderIPAddresses $CiscoIPs `",
                "            -RequireTls $true `",
                "            -Enabled $true `",
                "            -ErrorAction Stop",
                "    }",
                "} else { Write-Host \"$InboundConnectorName already exists.\" -ForegroundColor Yellow }",
                "",
                "# ── Bypass Spam Filter Rule ───────────────────────────",
                "if (-not (Get-TransportRule -Identity $BypassRuleName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $BypassRuleName {",
                "        New-TransportRule `",
                "            -Name $BypassRuleName `",
                "            -SenderIpRanges $CiscoIPs `",
                "            -SetSCL -1 `",
                "            -Mode Enforce `",
                "            -ErrorAction Stop",
                "    }",
                "} else { Write-Host \"$BypassRuleName already exists.\" -ForegroundColor Yellow }",
                "",
                "# ── Quarantine Rule ──────────────────────────────────",
                "if (-not (Get-TransportRule -Identity $QuarantineRuleName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $QuarantineRuleName {",
                "        New-TransportRule `",
                "            -Name $QuarantineRuleName `",
                "            -HeaderMatchesMessageHeader 'X-CSE-Quarantine' `",
                "            -HeaderMatchesPatterns 'true' `",
                "            -Quarantine $true `",
                "            -Mode Enforce `",
                "            -ErrorAction Stop",
                "    }",
                "} else { Write-Host \"$QuarantineRuleName already exists.\" -ForegroundColor Yellow }",
                "",
                "# ── Junk Rule ────────────────────────────────────────",
                "if (-not (Get-TransportRule -Identity $JunkRuleName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $JunkRuleName {",
                "        New-TransportRule `",
                "            -Name $JunkRuleName `",
                "            -HeaderMatchesMessageHeader 'X-CSE-Junk' `",
                "            -HeaderMatchesPatterns 'true' `",
                "            -SetSCL 9 `",
                "            -Mode Enforce `",
                "            -ErrorAction Stop",
                "    }",
                "} else { Write-Host \"$JunkRuleName already exists.\" -ForegroundColor Yellow }",
                "",
            ]

        if flows.get("outbound"):
            lines += [
                "# ── Outbound Connector ───────────────────────────────",
                "if (-not (Get-OutboundConnector -Identity $OutboundConnectorName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $OutboundConnectorName {",
                "        New-OutboundConnector `",
                "            -Name $OutboundConnectorName `",
                "            -ConnectorType Partner `",
                "            -IsTransportRuleScoped $true `",
                "            -SmartHosts $OutboundSmartHost `",
                "            -UseMXRecord $false `",
                "            -TlsSettings EncryptionOnly `",
                "            -Enabled $true `",
                "            -ErrorAction Stop",
                "    }",
                "} else { Write-Host \"$OutboundConnectorName already exists.\" -ForegroundColor Yellow }",
                "",
                "# ── Outbound Tag Rule (X-CSE-ETD-OUTBOUND-AUTH header) ─",
                "if (-not (Get-TransportRule -Identity $OutboundTagRuleName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $OutboundTagRuleName {",
                "        New-TransportRule `",
                "            -Name $OutboundTagRuleName `",
                "            -SentToScope NotInOrganization `",
                "            -RouteMessageOutboundConnector $OutboundConnectorName `",
                "            -SetHeaderName 'X-CSE-ETD-OUTBOUND-AUTH' `",
                "            -SetHeaderValue $XPassValue `",
                "            -Enabled $OutboundTagRuleEnabled `",
                "            -Mode Enforce `",
                "            -ErrorAction Stop",
                "    }",
                "} else { Write-Host \"$OutboundTagRuleName already exists.\" -ForegroundColor Yellow }",
                "",
            ]

        if flows.get("internal"):
            lines += [
                "# ── Journal Rule (Internal flow) ─────────────────────",
                "if (-not (Get-JournalRule -Identity $JournalRuleName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $JournalRuleName {",
                "        New-JournalRule `",
                "            -Name $JournalRuleName `",
                "            -JournalEmailAddress $JournalAddress `",
                "            -Scope Internal `",
                "            -Enabled $true `",
                "            -ErrorAction Stop",
                "    }",
                "} else { Write-Host \"$JournalRuleName already exists.\" -ForegroundColor Yellow }",
            ]

    else:  # Journaling mode
        lines += [
            "# ── Journaling Outbound Connector (MX direct) ────────",
            "if (-not (Get-OutboundConnector -Identity $JournalConnectorName -ErrorAction SilentlyContinue)) {",
            "    Install-Object $JournalConnectorName {",
            "        New-OutboundConnector `",
            "            -Name $JournalConnectorName `",
            "            -ConnectorType Partner `",
            "            -RecipientDomains $JournalDomain `",
            "            -UseMXRecord $true `",
            "            -Enabled $true `",
            "            -ErrorAction Stop",
            "    }",
            "} else { Write-Host \"$JournalConnectorName already exists.\" -ForegroundColor Yellow }",
            "",
            "# ── Journal Rule ─────────────────────────────────────",
            "if (-not (Get-JournalRule -Identity $JournalRuleName -ErrorAction SilentlyContinue)) {",
            "    Install-Object $JournalRuleName {",
            "        New-JournalRule `",
            "            -Name $JournalRuleName `",
            "            -JournalEmailAddress $JournalAddress `",
            "            -Scope Global `",
            "            -Enabled $true `",
            "            -ErrorAction Stop",
            "    }",
            "} else { Write-Host \"$JournalRuleName already exists.\" -ForegroundColor Yellow }",
        ]

    return lines


# ---------------------------------------------------------------------------
# REMOVE
# ---------------------------------------------------------------------------

def _remove_block(mode, flows):
    lines = []
    if mode == "Inline":
        if flows.get("inbound"):
            lines += [
                "Remove-Object $InboundConnectorName  { Get-InboundConnector -Identity $InboundConnectorName -ErrorAction Stop | Remove-InboundConnector -Confirm:$false }",
                "Remove-Object $BypassRuleName        { Get-TransportRule -Identity $BypassRuleName     -ErrorAction Stop | Remove-TransportRule -Confirm:$false }",
                "Remove-Object $QuarantineRuleName    { Get-TransportRule -Identity $QuarantineRuleName -ErrorAction Stop | Remove-TransportRule -Confirm:$false }",
                "Remove-Object $JunkRuleName          { Get-TransportRule -Identity $JunkRuleName       -ErrorAction Stop | Remove-TransportRule -Confirm:$false }",
            ]
        if flows.get("outbound"):
            lines += [
                "Remove-Object $OutboundConnectorName { Get-OutboundConnector -Identity $OutboundConnectorName -ErrorAction Stop | Remove-OutboundConnector -Confirm:$false }",
                "Remove-Object $OutboundTagRuleName   { Get-TransportRule -Identity $OutboundTagRuleName -ErrorAction Stop | Remove-TransportRule -Confirm:$false }",
            ]
        if flows.get("internal"):
            lines += [
                "Remove-Object $JournalRuleName { Get-JournalRule -Identity $JournalRuleName -ErrorAction Stop | Remove-JournalRule -Confirm:$false }",
            ]
    else:
        lines += [
            "Remove-Object $JournalRuleName     { Get-JournalRule -Identity $JournalRuleName -ErrorAction Stop | Remove-JournalRule -Confirm:$false }",
            "Remove-Object $JournalConnectorName { Get-OutboundConnector -Identity $JournalConnectorName -ErrorAction Stop | Remove-OutboundConnector -Confirm:$false }",
        ]
    return lines


# ---------------------------------------------------------------------------
# STEP-BY-STEP
# ---------------------------------------------------------------------------

def _step_preamble(config):
    """Return preamble lines (functions + variables + connect) for a single-step script."""
    mode      = config["deployment_mode"]
    admin_upn = config["admin_upn"]
    journal   = config["journal_address"]
    flows     = config.get("flows", {})
    etd_ips   = config.get("etd_ips", [])
    seg_front = config.get("seg_in_front", False)
    seg_ips   = config.get("seg_ips", [])
    source_ips = seg_ips if (seg_front and seg_ips) else etd_ips
    smart_host           = config.get("smart_host", "")
    outbound_rule_enabled = config.get("outbound_rule_enabled", True)
    xpass     = config.get("xpass_value", "12345")

    lines = [_ps_functions()]
    lines += [
        f'$AdminUPN          = "{admin_upn}"',
        f'$JournalAddress    = "{journal}"',
        f'$JournalNdrAddress = "{admin_upn}"',
    ]

    if mode == "Inline":
        if flows.get("inbound"):
            lines += [
                '$InboundConnectorName = "Cisco Secure Email Threat Defense Inbound"',
                '$BypassRuleName       = "Cisco Secure Email Threat Defense Bypass Spam Filter"',
                '$QuarantineRuleName   = "Cisco Secure Email Threat Defense Quarantine Rule"',
                '$JunkRuleName         = "Cisco Secure Email Threat Defense Junk Rule"',
            ]
        if flows.get("outbound"):
            rule_state = "$true" if outbound_rule_enabled else "$false"
            lines += [
                '$OutboundConnectorName  = "Cisco Secure Email Threat Defense Outbound"',
                '$OutboundTagRuleName    = "Cisco Secure Email Threat Defense Outbound Tag"',
                f'$OutboundSmartHost      = "{smart_host}"',
                f'$XPassValue             = "{xpass}"',
                f'$OutboundTagRuleEnabled = {rule_state}',
            ]
        if flows.get("internal"):
            lines += ['$JournalRuleName = "Cisco Secure Email Threat Defense"']
    else:
        lines += [
            '$JournalRuleName      = "Cisco Secure Email Threat Defense"',
            '$JournalConnectorName = "Cisco ETD Journaling Direct"',
            '$JournalDomain        = ($JournalAddress -split "@")[1]',
        ]

    if source_ips:
        lines += [f"$CiscoIPs = {_ps_array(source_ips)}"]

    lines += [
        "",
        'Write-Host ""',
        'Write-Host "Connecting to Exchange Online..." -ForegroundColor Cyan',
        "Connect-ExchangeOnline -UserPrincipalName $AdminUPN -ShowBanner:$false",
        "",
    ]
    return lines


def generate_steps(config):
    """
    Return [(step_name, mini_script), ...] for step-by-step installation.
    Each mini-script: connect → one action → disconnect.
    """
    mode      = config["deployment_mode"]
    flows     = config.get("flows", {})
    seg_front = config.get("seg_in_front", False)
    seg_ips   = config.get("seg_ips", [])
    etd_ips   = config.get("etd_ips", [])
    source_ips = seg_ips if (seg_front and seg_ips) else etd_ips

    needs_journal = (mode == "Journaling") or (mode == "Inline" and flows.get("internal"))

    epilogue = [
        "",
        "Disconnect-ExchangeOnline -Confirm:$false",
        'Write-Host ""',
        'Write-Host "Step completed." -ForegroundColor Cyan',
    ]

    def make(name, action_lines):
        lines = _step_preamble(config) + action_lines + epilogue
        return (name, "\n".join(lines))

    steps = []

    if needs_journal:
        steps.append(make("Journaling NDR Address", [
            "# ── Journaling NDR Address ───────────────────────────",
            "$tc = Get-TransportConfig",
            "if (-not $tc.JournalingReportNdrTo) {",
            '    Write-Host "Configuring Journaling NDR address..." -ForegroundColor Cyan',
            "    try {",
            "        Set-TransportConfig -JournalingReportNdrTo $JournalNdrAddress -ErrorAction Stop",
            '        Write-Host "Journaling NDR address set to $JournalNdrAddress" -ForegroundColor Green',
            "    } catch {",
            '        Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red',
            "        Disconnect-ExchangeOnline -Confirm:$false",
            "        exit 1",
            "    }",
            "} else {",
            '    Write-Host "Journaling NDR already configured: $($tc.JournalingReportNdrTo)" -ForegroundColor Green',
            "}",
        ]))

    if mode == "Inline":
        if flows.get("inbound"):
            steps.append(make("Inbound Connector", [
                "# ── Inbound Connector ────────────────────────────────",
                "if (-not (Get-InboundConnector -Identity $InboundConnectorName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $InboundConnectorName {",
                "        New-InboundConnector `",
                "            -Name $InboundConnectorName `",
                "            -ConnectorType Partner `",
                "            -SenderDomains '*' `",
                "            -SenderIPAddresses $CiscoIPs `",
                "            -RequireTls $true `",
                "            -Enabled $true `",
                "            -ErrorAction Stop",
                "    }",
                '} else { Write-Host "$InboundConnectorName already exists." -ForegroundColor Yellow }',
            ]))
            steps.append(make("Cisco Secure Email Threat Defense Bypass Spam Filter", [
                "# ── Bypass Spam Filter Rule ───────────────────────────",
                "if (-not (Get-TransportRule -Identity $BypassRuleName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $BypassRuleName {",
                "        New-TransportRule `",
                "            -Name $BypassRuleName `",
                "            -SenderIpRanges $CiscoIPs `",
                "            -SetSCL -1 `",
                "            -Mode Enforce `",
                "            -ErrorAction Stop",
                "    }",
                '} else { Write-Host "$BypassRuleName already exists." -ForegroundColor Yellow }',
            ]))
            steps.append(make("Cisco Secure Email Threat Defense Quarantine Rule", [
                "# ── Quarantine Rule ──────────────────────────────────",
                "if (-not (Get-TransportRule -Identity $QuarantineRuleName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $QuarantineRuleName {",
                "        New-TransportRule `",
                "            -Name $QuarantineRuleName `",
                "            -HeaderMatchesMessageHeader 'X-CSE-Quarantine' `",
                "            -HeaderMatchesPatterns 'true' `",
                "            -Quarantine $true `",
                "            -Mode Enforce `",
                "            -ErrorAction Stop",
                "    }",
                '} else { Write-Host "$QuarantineRuleName already exists." -ForegroundColor Yellow }',
            ]))
            steps.append(make("Cisco Secure Email Threat Defense Junk Rule", [
                "# ── Junk Rule ────────────────────────────────────────",
                "if (-not (Get-TransportRule -Identity $JunkRuleName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $JunkRuleName {",
                "        New-TransportRule `",
                "            -Name $JunkRuleName `",
                "            -HeaderMatchesMessageHeader 'X-CSE-Junk' `",
                "            -HeaderMatchesPatterns 'true' `",
                "            -SetSCL 9 `",
                "            -Mode Enforce `",
                "            -ErrorAction Stop",
                "    }",
                '} else { Write-Host "$JunkRuleName already exists." -ForegroundColor Yellow }',
            ]))

        if flows.get("outbound"):
            steps.append(make("Outbound Connector", [
                "# ── Outbound Connector ───────────────────────────────",
                "if (-not (Get-OutboundConnector -Identity $OutboundConnectorName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $OutboundConnectorName {",
                "        New-OutboundConnector `",
                "            -Name $OutboundConnectorName `",
                "            -ConnectorType Partner `",
                "            -IsTransportRuleScoped $true `",
                "            -SmartHosts $OutboundSmartHost `",
                "            -UseMXRecord $false `",
                "            -TlsSettings EncryptionOnly `",
                "            -Enabled $true `",
                "            -ErrorAction Stop",
                "    }",
                '} else { Write-Host "$OutboundConnectorName already exists." -ForegroundColor Yellow }',
            ]))
            steps.append(make("Cisco Secure Email Threat Defense Outbound Tag Rule", [
                "# ── Outbound Tag Rule ─────────────────────────────────",
                "if (-not (Get-TransportRule -Identity $OutboundTagRuleName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $OutboundTagRuleName {",
                "        New-TransportRule `",
                "            -Name $OutboundTagRuleName `",
                "            -SentToScope NotInOrganization `",
                "            -RouteMessageOutboundConnector $OutboundConnectorName `",
                "            -SetHeaderName 'X-CSE-ETD-OUTBOUND-AUTH' `",
                "            -SetHeaderValue $XPassValue `",
                "            -Enabled $OutboundTagRuleEnabled `",
                "            -Mode Enforce `",
                "            -ErrorAction Stop",
                "    }",
                '} else { Write-Host "$OutboundTagRuleName already exists." -ForegroundColor Yellow }',
            ]))

        if flows.get("internal"):
            steps.append(make("Journal Rule (Internal)", [
                "# ── Journal Rule (Internal flow) ─────────────────────",
                "if (-not (Get-JournalRule -Identity $JournalRuleName -ErrorAction SilentlyContinue)) {",
                "    Install-Object $JournalRuleName {",
                "        New-JournalRule `",
                "            -Name $JournalRuleName `",
                "            -JournalEmailAddress $JournalAddress `",
                "            -Scope Internal `",
                "            -Enabled $true `",
                "            -ErrorAction Stop",
                "    }",
                '} else { Write-Host "$JournalRuleName already exists." -ForegroundColor Yellow }',
            ]))

    else:  # Journaling mode
        steps.append(make("Journaling Outbound Connector", [
            "# ── Journaling Outbound Connector (MX direct) ────────",
            "if (-not (Get-OutboundConnector -Identity $JournalConnectorName -ErrorAction SilentlyContinue)) {",
            "    Install-Object $JournalConnectorName {",
            "        New-OutboundConnector `",
            "            -Name $JournalConnectorName `",
            "            -ConnectorType Partner `",
            "            -RecipientDomains $JournalDomain `",
            "            -UseMXRecord $true `",
            "            -Enabled $true `",
            "            -ErrorAction Stop",
            "    }",
            '} else { Write-Host "$JournalConnectorName already exists." -ForegroundColor Yellow }',
        ]))
        steps.append(make("Journal Rule", [
            "# ── Journal Rule ─────────────────────────────────────",
            "if (-not (Get-JournalRule -Identity $JournalRuleName -ErrorAction SilentlyContinue)) {",
            "    Install-Object $JournalRuleName {",
            "        New-JournalRule `",
            "            -Name $JournalRuleName `",
            "            -JournalEmailAddress $JournalAddress `",
            "            -Scope Global `",
            "            -Enabled $true `",
            "            -ErrorAction Stop",
            "    }",
            '} else { Write-Host "$JournalRuleName already exists." -ForegroundColor Yellow }',
        ]))

    return steps
